language: r
cache: packages

matrix:
  include:
  - r: release
    os: linux
    env: INSTALL_COBALT=true
  - r: devel
    os: linux
    env: INSTALL_COBALT=false

r_packages:
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  # COBALT
  #- if [[ "$INSTALL_COBALT" == true ]]; then ./scripts/install_cobalt.sh; fi
  # proselint
  - sudo pip install proselint

after_success:
  - if [[ "$INSTALL_COBALT" == true ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$INSTALL_COBALT" == true ]]; then Rscript -e 'goodpractice::gp()'; fi
  - if [[ "$INSTALL_COBALT" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$INSTALL_COBALT" == false ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - Rscript -e 'cobaltr::cobaltr_report()'
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  - Rscript -e 'remotes::install_github("richelbilderbeek/cobaltr")'
  - Rscript -e 'cobaltr::cobaltr_report()'
  - ls
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

