on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 28 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      matrix:
        include:
          - install_cobalt: "true" 
          - install_cobalt: "false"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_cran("pkgdown")
          remotes::install_cran("devtools")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Show COBALT
        env:
          INSTALL_COBALT: ${{ matrix.install_cobalt }}
        run: echo "$INSTALL_COBALT"

      - name: If statement on COBALT is true
        env:
          INSTALL_COBALT: ${{ matrix.install_cobalt }}
        run: if [[ "$INSTALL_COBALT" == true ]]; then echo "Yay!"; fi

      - name: Show location
        run: pwd

      - name: If statement on COBALT is false
        env:
          INSTALL_COBALT: ${{ matrix.install_cobalt }}
        run: if [[ "$INSTALL_COBALT" == false ]]; then echo "Nay!"; fi

      - name: Show COBALT install script
        env:
          INSTALL_COBALT: ${{ matrix.install_cobalt }}
        run: if [[ "$INSTALL_COBALT" == true ]]; then cat scripts/install_cobalt.sh; fi

      - name: Install COBALT
        env:
          INSTALL_COBALT: ${{ matrix.install_cobalt }}
        run: if [[ "$INSTALL_COBALT" == true ]]; then ./scripts/install_cobalt.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: if [[ "$INSTALL_COBALT" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        run: if [[ "$INSTALL_COBALT" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

      - name: Install cobaltr
        run: remotes::install_github("richelbilderbeek/cobaltr")
        shell: Rscript {0}

      - name: Report
        run: cobaltr::cobaltr_report()
        shell: Rscript {0}

